/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tugas1_login;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.NumberFormat;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ACER
 */
public class beli_sekarang extends javax.swing.JFrame {
    static int total_harga = 0;
    public int simpan_harga = 0;
    public int stock_barang = 0 ;
//    public int Updatestock_barang = 0 ;
    public int jumlah_barang = 0 ;
    public void ambil_data(){
        try {
            System.out.println("ini id obat beli sekarang" + menu_pesanan_user.idObat);
            String sql = "Select nama_obat,harga_obat, stock_obat, jenis_obat, ketersediaan, dosis, expired_obat, deskripsi_obat From dataobat where id_obat= ?";
            Connection conn = koneksi.koneksiDB();
            PreparedStatement statement = conn.prepareStatement(sql);
            statement.setInt(1, menu_pesanan_user.idObat);
            ResultSet rs = statement.executeQuery();            
            while(rs.next()){                                                
                if(menu_pesanan_user.idObat == menu_pesanan_user.idObat){
                    String nama_obat = rs.getString("nama_obat");
                    String harga_obat = rs.getString("harga_obat");
                    String stock_obat = rs.getString("stock_obat");
                    String jenis_obat = rs.getString("jenis_obat");                                
                    String dosis = rs.getString("dosis");
                    Date expired_obat = rs.getDate("expired_obat");
                    String deskripsi_obatt = rs.getString("deskripsi_obat");                    
                    namaobat.setText(nama_obat);                    
                    NumberFormat formatRupiah = NumberFormat.getCurrencyInstance(new Locale("id", "ID"));
                    String totalHargaRupiah = formatRupiah.format(Double.parseDouble(harga_obat));
                    harga_obatt.setText(totalHargaRupiah);

                    //namaobat.setText(nama_obat);
                    jenisobat.setText(jenis_obat);
                    dosisobat.setText(dosis);
                    expiredobat.setText(expired_obat.toString());
                    deskripsi_obat.setText(deskripsi_obatt); 
                    break;
                }
                //System.out.println("datanya" + menu_pesanan_user.idObat);
            }            
        } catch (SQLException ex) {
            Logger.getLogger(menu_pesanan_user.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * Creates new form beli_sekarang
     */
    public beli_sekarang() {
        initComponents();
        ambil_data();
        deskripsi_obat.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        txtJumlah = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnBeli = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        namaobat = new javax.swing.JLabel();
        jenisobat = new javax.swing.JLabel();
        dosisobat = new javax.swing.JLabel();
        expiredobat = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        deskripsi_obat = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        harga_obatt = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAlamat = new javax.swing.JTextArea();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtJumlah.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtJumlahFocusLost(evt);
            }
        });
        txtJumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJumlahActionPerformed(evt);
            }
        });
        txtJumlah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtJumlahKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        jLabel1.setText("Nama Obat    :");

        jLabel2.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        jLabel2.setText("Jenis Obat     :");

        jLabel3.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        jLabel3.setText("Jumlah Barang");

        jLabel4.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        jLabel4.setText("Dosis              :");

        jLabel5.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        jLabel5.setText("Expired Obat :");

        btnBeli.setText("Beli Sekarang");
        btnBeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBeliActionPerformed(evt);
            }
        });

        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        namaobat.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        namaobat.setText("Nama Obat");

        jenisobat.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        jenisobat.setText("Nama Obat");

        dosisobat.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        dosisobat.setText("Dosis");

        expiredobat.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        expiredobat.setText("Expired Obat");

        jLabel6.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        jLabel6.setText("Deskripsi Obat:");

        deskripsi_obat.setColumns(20);
        deskripsi_obat.setRows(5);
        jScrollPane1.setViewportView(deskripsi_obat);

        jLabel7.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        jLabel7.setText("Harga Obat   :");

        harga_obatt.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        harga_obatt.setText("Nama Obat");

        jLabel8.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        jLabel8.setText("Alamat Pemesan:");

        txtAlamat.setColumns(20);
        txtAlamat.setRows(5);
        jScrollPane3.setViewportView(txtAlamat);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel7))
                                .addGap(27, 27, 27))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(25, 25, 25)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jenisobat)
                                    .addComponent(namaobat)
                                    .addComponent(harga_obatt))
                                .addGap(77, 77, 77)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(expiredobat)
                                    .addComponent(dosisobat)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(28, 28, 28)
                        .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(btnBeli, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(namaobat)
                    .addComponent(dosisobat))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(expiredobat)
                    .addComponent(jenisobat)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(jLabel7)
                        .addComponent(harga_obatt))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBeli, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBeliActionPerformed
        if(txtAlamat.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Silahkan isi alamat", "Data belum lengkap", JOptionPane.INFORMATION_MESSAGE);
            txtAlamat.requestFocus();
            return;
        }
        else if(txtJumlah.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Silahkan isi jumlah barang", "Data belum lengkap", JOptionPane.INFORMATION_MESSAGE);
            txtJumlah.requestFocus();
            return;
        }
        try {
               String sql = "Select * from dataobat where id_obat= ?";
               Connection conn = koneksi.koneksiDB();
               PreparedStatement statement = conn.prepareStatement(sql);
               statement.setInt(1, menu_pesanan_user.idObat);
               ResultSet rs = statement.executeQuery();
               while(rs.next()){
                   if(menu_pesanan_user.idObat == menu_pesanan_user.idObat){
                       String username = Logininterface.usernamee;
                       int idobat = rs.getInt("id_obat");
                       String nama_obat = rs.getString("nama_obat");
                       String jenis_obat = rs.getString("jenis_obat");
                       //String ketersediaan = rs.getString("ketersediaan");
                       String dosis = rs.getString("dosis");
                       Date expired_obat = rs.getDate("expired_obat");
                       int hargaobatt = rs.getInt("harga_obat");

                       
                       String insertQuery = "INSERT INTO pesanan_user (id_obat, username, nama_obat, jenis_obat, dosis, expired_obat, jumlah_barang, harga_obat, alamat_pesanan) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";
                       PreparedStatement inserstatment = conn.prepareStatement(insertQuery);
                       inserstatment.setInt(1, idobat);
                       inserstatment.setString(2, username);
                       inserstatment.setString(3, nama_obat);
                       inserstatment.setString(4, jenis_obat);
                       inserstatment.setString(5, dosis);                               
                       inserstatment.setDate(6, new java.sql.Date(expired_obat.getTime()));
                       inserstatment.setString(7, txtJumlah.getText());                                       
                       inserstatment.setInt(8, simpan_harga);                                       
                       inserstatment.setString(9, txtAlamat.getText()); 
                       
                       String updatestockbarang = "Update dataobat Set stock_obat=? where id_obat= ?";                       
                       PreparedStatement updatestatmen = conn.prepareStatement(updatestockbarang);                       
                       updatestatmen.setInt(1, stock_barang);
                       updatestatmen.setInt(2, menu_pesanan_user.idObat);
                       updatestatmen.executeUpdate();
                       if (txtJumlah.getText().isEmpty()){
                           JOptionPane.showMessageDialog(null, "Harap isi jumlah barangt.", "Peringatan", JOptionPane.WARNING_MESSAGE);
                           return;
                       }
                       int confirm = JOptionPane.showConfirmDialog(null, "Anda yakin ingin melakukan pembelian?", "Konfirmasi Pembelian", JOptionPane.YES_NO_OPTION);
                       if (confirm == JOptionPane.YES_OPTION) {
                           inserstatment.executeUpdate();
                           JOptionPane.showMessageDialog(null, "Berhasil Membeli Obat", "Success", JOptionPane.INFORMATION_MESSAGE);
                       } 
                       break;
                   }                

               }
           } catch (SQLException ex) {               
               Logger.getLogger(menu_pesanan_user.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_btnBeliActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        menu_pesanan_user keluar = new menu_pesanan_user();
        keluar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBatalActionPerformed

    private void txtJumlahKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJumlahKeyPressed

    }//GEN-LAST:event_txtJumlahKeyPressed

    private void txtJumlahFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtJumlahFocusLost
        String total_barangg = txtJumlah.getText();        
        jumlah_barang = Integer.parseInt(total_barangg);                
        String stockbarangstring = String.valueOf(menu_pesanan_user.stock_barang);
        if(jumlah_barang > menu_pesanan_user.stock_barang){
            txtJumlah.setText(stockbarangstring);
            JOptionPane.showMessageDialog(null, "Anda Melebihi Stock Barang");
        }
        else{
            int total_hargay = jumlah_barang * total_harga;        
            NumberFormat formatRupiah = NumberFormat.getCurrencyInstance(new Locale("id", "ID"));
            String totalHargaRupiah = formatRupiah.format(total_hargay);
            harga_obatt.setText(String.valueOf(totalHargaRupiah));
            simpan_harga = total_hargay;
            stock_barang = menu_pesanan_user.stock_barang - jumlah_barang;

        }                        
    }//GEN-LAST:event_txtJumlahFocusLost

    private void txtJumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJumlahActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(beli_sekarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(beli_sekarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(beli_sekarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(beli_sekarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new beli_sekarang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnBeli;
    private javax.swing.JTextArea deskripsi_obat;
    private javax.swing.JLabel dosisobat;
    private javax.swing.JLabel expiredobat;
    private javax.swing.JLabel harga_obatt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel jenisobat;
    private javax.swing.JLabel namaobat;
    private javax.swing.JTextArea txtAlamat;
    private javax.swing.JTextField txtJumlah;
    // End of variables declaration//GEN-END:variables
}
